<?php 
/**
	Admin Page Framework v3.8.34 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/index-wp-mysql-for-speed>
	Copyright (c) 2013-2021, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class Imfs_AdminPageFramework_Form_View___CSS_CollapsibleSectionIE extends Imfs_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getCollapsibleSectionsRules();
    }
    private function _getCollapsibleSectionsRules() {
        return "tbody.index-wp-mysql-for-speed-collapsible-content > tr > th,tbody.index-wp-mysql-for-speed-collapsible-content > tr > td{padding-right: 20px;padding-left: 20px;}";
    }
    }
    