<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class IndexMySQLForSpeedAdmin {
	private $index_mysql_for_speed_options;
	private $db;
	private string $page;


	public function __construct( $page = 'index_mysql_for_speed_admin' ) {
		add_action( 'admin_menu', array( $this, 'index_mysql_for_speed_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'index_mysql_for_speed_page_init' ) );
		$this->db   = new ImfsDb();
		$this->page = $page;

		$nonce = wp_create_nonce();
	}

	public function index_mysql_for_speed_add_plugin_page() {
		load_plugin_textdomain( index_wp_mysql_for_speed_domain,
			false, '../languages/' );

		add_options_page(
		/* translators: admin page title */
			__( 'Index MySQL for speed', index_wp_mysql_for_speed_domain ),
			/* translators: admin page menu title */
			__( 'Index MySQL', index_wp_mysql_for_speed_domain ), // menu_title
			'manage_options', // capability
			'index-mysql-for-speed', // menu_slug
			array( $this, 'index_mysql_for_speed_create_admin_page' ) // function
		);
	}

	public function index_mysql_for_speed_create_admin_page() {

		wp_enqueue_style( index_wp_mysql_for_speed_PLUGIN_NAME . 'css',
			plugin_dir_url( __FILE__ ) . 'assets/imfs.css' );
		wp_enqueue_script( index_wp_mysql_for_speed_PLUGIN_NAME . 'js',
			plugin_dir_url( __FILE__ ) . 'assets/imfs.js' );

		$this->index_mysql_for_speed_options = get_option( 'index_mysql_for_speed_option_name' ); ?>

        <div class="wrap">
            <h2><?php __( 'Index MySQL for speed', index_wp_mysql_for_speed_domain ) ?></h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ultrices luctus nunc vitae elementum.
                Morbi vitae tellus porta, suscipit magna eu.</p>
			<?php settings_errors(); ?>

            <form method="post" action="options.php">
				<?php
				settings_fields( 'index_mysql_for_speed_option_group' );
				do_settings_sections( $this->page );
				submit_button();
				?>
            </form>
        </div>
	<?php }

	public function index_mysql_for_speed_page_init() {
		register_setting(
			'index_mysql_for_speed_option_group', // option_group
			'index_mysql_for_speed_option_name', // option_name
			array( $this, 'index_mysql_for_speed_sanitize' ) // sanitize_callback
		);
		$section = 'index_mysql_for_speed_permission_section';
		add_settings_section(
			$section, // id
			__( 'Permission', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'index_mysql_for_speed_permission_info' ), // callback
			$this->page // page
		);
		add_settings_field(
			'telemetry_0', // id
			__( 'Upload', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'telemetry_0_callback' ), // callback
			$this->page, // page
			$section
		);

//		$this->addField(
//			'telemetry_0', // id
//			'Upload',
//			"Check this to allow us to gather anonymous information about your WordPress data. We do not gather your data, just information about it.
//	    We use your information for just one purpose: improving future versions of the plugin. We never sell it or share it,
//	    and we cannot identify you or your WordPress instance from it.",
//			'checkbox', 'telemetry',
//			$this->page,
//			$section
//		);

		$section = 'index_mysql_for_speed_setting_section';
		add_settings_section(
			$section, // id
			__( 'Settings', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'index_mysql_for_speed_section_info' ), // callback
			$this->page
		);


		add_settings_field(
			'all_1',
			__( 'Index all tables', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'all_1_callback' ), // callback
			$this->page, $section
		);

		add_settings_field(
			'postmeta_2', // id
			__( 'Index wp_postmeta', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'postmeta_2_callback' ), // callback
			$this->page, $section
		);

		add_settings_field(
			'usermeta_3', // id
			__( 'Index wp_usermeta', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'usermeta_3_callback' ), // callback
			$this->page, $section
		);

		add_settings_field(
			'termmeta_4', // id
			__( 'Index wp_termmeta', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'termmeta_4_callback' ), // callback
			$this->page, $section
		);

		add_settings_field(
			'options_5', // id
			__( 'Index wp_options', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'options_5_callback' ), // callback
			$this->page, $section
		);

		add_settings_field(
			'posts_6', // id
			__( 'Index wp_posts ', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'posts_6_callback' ), // callback
			$this->page, $section
		);

		add_settings_field(
			'comments_7', // id
			__( 'Index wp_comments', index_wp_mysql_for_speed_domain ), // title
			array( $this, 'comments_7_callback' ), // callback
			$this->page, $section
		);
	}

	public function addField(
		$id, $title, $description,
		$renderCallback, $inputClass, $section,
		$domain = index_wp_mysql_for_speed_domain
	) {
		$title       = __( $title, $domain );
		$description = __( $description, $domain );
		add_settings_field(
			$id,
			$title,
			array( $this, $renderCallback ), // callback
			$this->page, $section,
			array(
				'type'        => $renderCallback,
				'description' => $description,
				'name'        => $id,
				'inputClass'  => $inputClass
			)
		);

	}

	public function index_mysql_for_speed_permission_info() {

	}

	public function checkbox( $args ) {
		$txt = __( "
	    Check this to allow us to gather anonymous information about your WordPress data. We do not gather your data, just information about it.
	    We use your information for just one purpose: improving future versions of the plugin. We never sell it or share it,
	    and we cannot identify you or your WordPress instance from it.
	    ", index_wp_mysql_for_speed_domain );
		echo $this->renderCheckbox( $args['id'], $args['description'], $args['inputClass'] );
	}

	public function index_mysql_for_speed_sanitize( $input ) {
		$sanitary_values = array();
		if ( isset( $input['telemetry_0'] ) ) {
			$sanitary_values['telemetry_0'] = $input['telemetry_0'];
		}

		if ( isset( $input['all_1'] ) ) {
			$sanitary_values['all_1'] = $input['all_1'];
		}

		if ( isset( $input['postmeta_2'] ) ) {
			$sanitary_values['postmeta_2'] = $input['postmeta_2'];
		}

		if ( isset( $input['usermeta_3'] ) ) {
			$sanitary_values['usermeta_3'] = $input['usermeta_3'];
		}

		if ( isset( $input['termmeta_4'] ) ) {
			$sanitary_values['termmeta_4'] = $input['termmeta_4'];
		}

		if ( isset( $input['options_5'] ) ) {
			$sanitary_values['options_5'] = $input['options_5'];
		}

		if ( isset( $input['posts_6'] ) ) {
			$sanitary_values['posts_6'] = $input['posts_6'];
		}

		if ( isset( $input['comments_7'] ) ) {
			$sanitary_values['comments_7'] = $input['comments_7'];
		}

		return $sanitary_values;
	}

	public function index_mysql_for_speed_section_info() {

	}

	public string $checkboxTemplate = '<input type="checkbox" 
                           name="index_mysql_for_speed_option_name[%1$s]"
                           class="imfs imfs_checkbox %4$s"
                           id="%1$s"
                           value="%1$s" %2$s></td><td>
                    <label for="%1$s">%3$s</label></td>';

	public function renderCheckbox( $field, $text, $class = '' ): string {
		return sprintf(
			$this->checkboxTemplate,
			$field,
			( isset( $this->index_mysql_for_speed_options[ $field ] ) && $this->index_mysql_for_speed_options[ $field ] === $field ) ? 'checked' : '',
			$text, $class
		);

	}

	public function telemetry_0_callback() {
	    $txt = __("
	    Check this to allow us to gather anonymous information about your WordPress data. 
	    We use your information for just one purpose: improving future versions of the plugin. We never sell it or share it,
	    and we cannot identify you or your WordPress instance from it.
	    ",  index_wp_mysql_for_speed_domain);
	    echo $this->renderCheckbox('telemetry_0', $txt, 'telemetry');
	}

	public function all_1_callback( $args ) {
		$txt = __( "
	    Check this to update the keys on all tables below.
	    ", index_wp_mysql_for_speed_domain );

		echo $this->renderCheckbox( 'all_1', $txt, 'index all' );
	}

	public function postmeta_2_callback() {
		$txt = __( "
	    This table is used by themes and plugins for information related to your WordPress posts and other content.
	    ", index_wp_mysql_for_speed_domain );

		echo $this->renderCheckbox( 'postmeta_2', $txt, 'index some' );
	}

	public function usermeta_3_callback() {
		$txt = __( "
	    This table is used by themes and plugins for information related to your registered users.
	    ", index_wp_mysql_for_speed_domain );

		echo $this->renderCheckbox( 'usermeta_3', $txt, 'index some' );
	}

	public function termmeta_4_callback() {
		$txt = __( "
	    This table is used by themes and plugins for categories and tags.
	    ", index_wp_mysql_for_speed_domain );

		echo $this->renderCheckbox( 'termmeta_4', $txt, 'index some' );
	}

	public function options_5_callback() {
		$txt = __( "
	    This table is used, very frequently, by WordPress and its themes and plugins to store all sorts of options.
	    ", index_wp_mysql_for_speed_domain );

		echo $this->renderCheckbox( 'options_5', $txt, 'index some' );
	}

	public function posts_6_callback() {
		$txt = __( "
	    This table is used by WordPress and its themes and plugins to store your posts, pages, media, and other content.
	    ", index_wp_mysql_for_speed_domain );

		echo $this->renderCheckbox( 'posts_6', $txt, 'index some' );
	}

	public function comments_7_callback() {
		$txt = __( "
	    This table is used by WordPress and its themes and plugins to store comments and reviews from site visitors.
	    ", index_wp_mysql_for_speed_domain );

		echo $this->renderCheckbox( 'comments_7', $txt, 'index some' );
	}

}

if ( is_admin() ) {
	$index_mysql_for_speed = new IndexMySQLForSpeedAdmin();
}

/*
 * Retrieve this value with:
 * $index_mysql_for_speed_options = get_option( 'index_mysql_for_speed_option_name' ); // Array of All Options
 * $telemetry_0 = $index_mysql_for_speed_options['telemetry_0']; // telemetry
 * $all_1 = $index_mysql_for_speed_options['all_1']; // all
 * $postmeta_2 = $index_mysql_for_speed_options['postmeta_2']; // postmeta
 * $usermeta_3 = $index_mysql_for_speed_options['usermeta_3']; // usermeta
 * $termmeta_4 = $index_mysql_for_speed_options['termmeta_4']; // termmeta
 * $options_5 = $index_mysql_for_speed_options['options_5']; // options
 * $posts_6 = $index_mysql_for_speed_options['posts_6']; // posts
 * $comments_7 = $index_mysql_for_speed_options['comments_7']; // comments
 */
