<?php 
/**
	Admin Page Framework v3.8.34 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/index-wp-mysql-for-speed>
	Copyright (c) 2013-2021, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class Imfs_AdminPageFramework_Form_View___Attribute_SectionTableBody extends Imfs_AdminPageFramework_Form_View___Attribute_Base {
    public $sContext = 'section_table_content';
    protected function _getAttributes() {
        $_sCollapsibleType = $this->getElement($this->aArguments, array('collapsible', 'type'), 'box');
        return array('class' => $this->getAOrB($this->aArguments['_is_collapsible'], 'index-wp-mysql-for-speed-collapsible-section-content' . ' ' . 'index-wp-mysql-for-speed-collapsible-content' . ' ' . 'accordion-section-content' . ' ' . 'index-wp-mysql-for-speed-collapsible-content-type-' . $_sCollapsibleType, null),);
    }
    }
    